---
title: "Data Import"
output: github_document
---

```{r setup, echo = FALSE, message = FALSE}
library(tidyverse)
library(readxl)
library(haven)
```

this document will show how to import data


# import the FAS litters CSV

```{r}
litters_df = read_csv("data/FAS_litters.csv")

litters_df = janitor::clean_names(litters_df)
```
# look at the dataset

```{r}
litters_df

head(litters_df)
tail(litters_df, 10)
```

```{r eval = FALSE}
view(litters_df)
```

# import FAS pups data (relative and absolute)

```{r}
pups_df = read_csv("data/FAS_pups.csv")

pups_df = janitor::clean_names(pups_df)

pups_df
```
```{r, eval = FALSE}
pups_df = read_csv(file = "~/Desktop/data_wrangling_i/data/FAS_litters.csv")
```
# look at read_csv options

col_names and skipping rows

```{r}
litters_df
  read_csv(
    file = "data/FAS_litters.csv",
    col_names = FALSE,
    skip = 1
  )
```

what about missing data

```{r}
litters_df
  read_csv(
    file = "data/FAS_litters.csv",
    na = c("NA", "", ".")
  )
  
litters_df = janitor::clean_names(litters_df)
  
pull(litters_df, gd0_weight)
```

what if we code 'group' as a factor variable

```{r}
litters_df
  read_csv(
    file = "data/FAS_litters.csv",
    na = c("NA", "", "."),
    col_types = cols(
      Group = col_factor()
    )
  )
```

# import an excel file

import the MLB 2011 summary data

```{r}
mlb_df = read_excel("data/mlb11.xlsx", sheet = mlb11)
```

# import sas data

```{r}
pulse_df = read_sas("data/public_pulse_data.sas7bdat")
```

# never use read.csv()

```{r}
litters_df = read.csv("data/FAS_litters.csv")
```

never do this either
```{r}
litters_df$L
```


