---
title: "Data Manipulation"
author: "Mia Isaacs"
date: "2024-09-19"
output: html_document
---

# load library

```{r setup, echo = FALSE, message = FALSE}
library(tidyverse)
```

import the two datasets that we're going to manipulate

# load litters dataset and clean names

```{r}
options(tibble.print_min = 3)

litters_df = 
    read_csv("./data/FAS_litters.csv", na = c("NA", ".", ""))

litters_df = 
    janitor::clean_names(litters_df)
```

# load pups dataset and clean names

```{r}
pups_df = 
    read_csv("data/FAS_pups.csv", na = c("NA", "."))
    
pups_df = 
    janitor::clean_names(pups_df)
```
    
# use select function

use select() to select variables

```{r}
select(litters_df, group, litter_number, gd0_weight, pups_born_alive)
```

```{r}
select(litters_df, group:gd_of_birth)
```

```{r}
select(litters_df, -pups_survive)
```

```{r}
select(litters_df, -(group:gd18_weight))
```
```{r}
select(litters_df, starts_with("gd"))

select(litters_df, contains("pups"))
```
```{r}
select(litters_df, GROUP = group, LiTtEr_NuMbEr = litter_number)

rename(litters_df, GROUP = group, LiTtEr_NuMbEr = litter_number)

select(litters_df, litter_number, gd0_weight, everything())

relocate(litters_df, litter_number, gd0_weight)
```
```{r}
select(pups_df, litter_number, sex, pd_ears)
```

# use filter function

```{r}
filter(litters_df, gd_of_birth == 20)
filter(litters_df, gd_of_birth == 19)
```
```{r}
filter(litters_df, pups_born_alive >= 8)
```
```{r}
filter(litters_df, pups_born_alive != 9)
```
```{r}
filter(litters_df, group == "Con7")
filter(litters_df,  group %in% c("Low7", "Low8"))
```
```{r}
filter(litters_df, group %in% c("Low7", "Low8"),  pups_born_alive == 8)
```
```{r}
drop_na(litters_df,gd0_weight)
```
```{r}
filter(pups_df, sex == 1)
```

```{r}
filter(pups_df, sex == 2, pd_walk < 11)
```

# use mutate function


# use arrange function


# PIPING






